# Generated by Django 3.2.15 on 2023-07-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0004_author_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='rating',
        ),
        migrations.AddField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(default=1995),
        ),
    ]
