# Generated by Django 3.2.15 on 2023-07-11 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0005_auto_20230711_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rating',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(null=True),
        ),
    ]
