# Generated by Django 3.2.15 on 2023-07-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0006_auto_20230711_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
