# Generated by Django 3.2.15 on 2023-07-15 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0015_auto_20230715_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book_app.author'),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_published',
            field=models.IntegerField(null=True),
        ),
    ]
