# Generated by Django 3.2.15 on 2023-07-24 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dummy_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movies',
            old_name='title',
            new_name='name',
        ),
    ]
